CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    login VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(60) NOT NULL,
    patronymic VARCHAR(60)
);